#
# Copyright 2020 ZUP IT SERVICOS EM TECNOLOGIA E INOVACAO SA
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

name: Beagle Angular 9 Automated Tests

#on: workflow_dispatch
on:
  push:
    branches:
      - master
    paths:
      - 'automated-tests/**'
      - '.github/**'
  pull_request:
    branches:
      - master
    paths:
      - 'automated-tests/**'
      - '.github/**'

jobs:
  angular9_tests:
    name: Main job
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Checkout Beagle repository to run BFF
        uses: actions/checkout@v2
        with:
          repository: ZupIT/beagle
          path: beagle-repository

      - name: Build and start BFF
        working-directory: beagle-repository
        run: |
          backend/gradlew -p backend automated-tests:bootJar
          nohup java -jar backend/automated-tests/build/libs/automated-tests.jar 2>&1 &

      - name: Clear yarn cache
        run: yarn cache clean

      - name: Compile and run angular 9 app
        working-directory: automated-tests/angular9
        run: |
          yarn
          nohup yarn start 2>&1 &

      - name: Run angular 9 app tests
        working-directory: automated-tests/common
        run: |
          yarn
          yarn test:angular:9

      - name: Expose failed test screenshot files
        if: failure()
        uses: actions/upload-artifact@v2
        with:
          name: failed_tests_screenshots
          path: automated-tests/common/cypress/screenshots
      



          